#include <iostream>

#include <SFML/Graphics.hpp>

#include "grass_tileset_map.hpp"

#define GRASS1_SPRITE 0
#define GRASS1_NORTHWEST_INNER_CORNER_SPRITE 1
#define GRASS1_NORTH_TRANSITION_SPRITE 2
#define GRASS1_NORTHEAST_INNER_CORNER_SPRITE 3
#define GRASS1_NORTHWEST_OUTER_CORNER_SPRITE 4
#define GRASS1_NORTHEAST_OUTER_CORNER_SPRITE 5
#define SAND1_SPRITE 6
#define SAND1_TEXTURED_SPRITE 7
#define SAND1_TEXTURED2_SPRITE 8
#define GRASS1_TEXTURED_SPRITE 9
#define GRASS1_WEST_TRANSITION_SPRITE 10
#define GRASS1_EAST_TRANSITION_SPRITE 12
#define GRASS1_SOUTHWEST_OUTER_CORNER_SPRITE 13
#define GRASS1_SOUTHEAST_OUTER_CORNER_SPRITE 14
#define SAND2_SPRITE 15
#define SAND2_TEXTURED_SPRITE 16
#define SAND2_TEXTURED2_SPRITE 17
#define GRASS1_TEXTURED2_SPRITE 18
#define GRASS1_SOUTHWEST_INNER_CORNER_SPRITE 19
#define GRASS1_SOUTH_TRANSITION_SPRITE 20
#define GRASS1_SOUTHEAST_INNER_CORNER_SPRITE 21
#define SAND2_SPRITE 24
#define SAND2_TEXTURED_SPRITE 25
#define SAND2_TEXTURED2_SPRITE 26

void init_textures();
sf::Sprite get_sprite(int);